VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "InternalMPClass"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = True
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = True
Option Explicit
Public UserID As String
Public TokenAPP As String
Public StoreID As Long
Public StoreName As String
Public ExtStoreID As String
Public FecCre As Date
Public EndPoint As String
Public Branchs As InternalBranchs
